[debug] [2018-09-02T11:44:28.163Z] ----------------------------------------------------------------------
[debug] [2018-09-02T11:44:28.165Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-09-02T11:44:28.166Z] CLI Version:   4.2.0
[debug] [2018-09-02T11:44:28.166Z] Platform:      darwin
[debug] [2018-09-02T11:44:28.166Z] Node Version:  v8.11.3
[debug] [2018-09-02T11:44:28.166Z] Time:          Sun Sep 02 2018 14:44:28 GMT+0300 (+03)
[debug] [2018-09-02T11:44:28.166Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-09-02T11:44:28.177Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-09-02T11:44:28.178Z] > authorizing via signed-in user
[debug] [2018-09-02T11:44:28.179Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:29.010Z] <<< HTTP RESPONSE 200
[debug] [2018-09-02T11:44:29.011Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:30.012Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/ahmetakkoc/linkitylinkfirebase'...
[info] 
[debug] [2018-09-02T11:44:31.178Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:48:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2018-09-02T11:44:43.385Z] ----------------------------------------------------------------------
[debug] [2018-09-02T11:44:43.387Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-09-02T11:44:43.387Z] CLI Version:   4.2.0
[debug] [2018-09-02T11:44:43.387Z] Platform:      darwin
[debug] [2018-09-02T11:44:43.387Z] Node Version:  v8.11.3
[debug] [2018-09-02T11:44:43.388Z] Time:          Sun Sep 02 2018 14:44:43 GMT+0300 (+03)
[debug] [2018-09-02T11:44:43.388Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-09-02T11:44:43.399Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-09-02T11:44:43.399Z] > authorizing via signed-in user
[debug] [2018-09-02T11:44:43.401Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:44.259Z] <<< HTTP RESPONSE 200
[debug] [2018-09-02T11:44:44.260Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:45.679Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/ahmetakkoc/linkitylinkfirebase'...
[info] 
[debug] [2018-09-02T11:44:46.910Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:48:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2018-09-02T11:44:53.564Z] ----------------------------------------------------------------------
[debug] [2018-09-02T11:44:53.567Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-09-02T11:44:53.567Z] CLI Version:   4.2.0
[debug] [2018-09-02T11:44:53.567Z] Platform:      darwin
[debug] [2018-09-02T11:44:53.567Z] Node Version:  v8.11.3
[debug] [2018-09-02T11:44:53.567Z] Time:          Sun Sep 02 2018 14:44:53 GMT+0300 (+03)
[debug] [2018-09-02T11:44:53.567Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-09-02T11:44:53.578Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-09-02T11:44:53.578Z] > authorizing via signed-in user
[debug] [2018-09-02T11:44:53.580Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:54.489Z] <<< HTTP RESPONSE 200
[debug] [2018-09-02T11:44:54.490Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/linkitylinkalpha  
 
[debug] [2018-09-02T11:44:55.509Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/ahmetakkoc/linkitylinkfirebase'...
[info] 
[debug] [2018-09-02T11:44:56.547Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:48:12)
[error] 
[error] Error: An unexpected error has occurred.
